open-v2x/dandelion

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/feature-request.md
- .github/workflows/commitlint.yml
- .github/workflows/dprint-check-action.yml
- .github/workflows/sync.yml
- README-zh_CN.rst
- README.rst
- dprint.json
- add commitlint & dprint workflows
- format markdown files
- format rst files
closes: #3
> ci: add commitlint & dprint workflows

- dandelion/api/api_v1/endpoints/rsus.py
- dandelion/crud/crud_rsu.py
- swagger.json
Edgeview needs enabled filter for list rsus.
> fix: add missing filter enabled for rsu list

- dandelion/api/api_v1/endpoints/areas.py
- dandelion/api/api_v1/endpoints/cameras.py
- dandelion/api/api_v1/endpoints/cities.py
- dandelion/api/api_v1/endpoints/countries.py
- dandelion/api/api_v1/endpoints/edge_node_rsus.py
- dandelion/api/api_v1/endpoints/edge_nodes.py
- dandelion/api/api_v1/endpoints/map_rsus.py
- dandelion/api/api_v1/endpoints/maps.py
- dandelion/api/api_v1/endpoints/mngs.py
- dandelion/api/api_v1/endpoints/provinces.py
- dandelion/api/api_v1/endpoints/radars.py
- dandelion/api/api_v1/endpoints/rsi_clcs.py
- dandelion/api/api_v1/endpoints/rsi_cwms.py
- dandelion/api/api_v1/endpoints/rsi_dnps.py
- dandelion/api/api_v1/endpoints/rsi_events.py
- dandelion/api/api_v1/endpoints/rsi_sdss.py
- dandelion/api/api_v1/endpoints/rsm_participants.py
- dandelion/api/api_v1/endpoints/rsu_configs.py
- dandelion/api/api_v1/endpoints/rsu_logs.py
- dandelion/api/api_v1/endpoints/rsu_models.py
- dandelion/api/api_v1/endpoints/rsu_queries.py
- dandelion/api/api_v1/endpoints/rsu_tmps.py
- dandelion/api/api_v1/endpoints/rsus.py
- swagger.json
> chore: Rename list function name as list_xxx

- .github/workflows/ci.yml
> ci: add deploy to aio step in ci workflow

- dandelion/models/rsu.py
- dandelion/schemas/rsu.py
- swagger.json
> fix: add "rsuModelName" to RSU detailed results

- dandelion/api/api_v1/endpoints/cameras.py
- dandelion/api/api_v1/endpoints/radars.py
- dandelion/crud/crud_camera.py
- dandelion/crud/crud_radar.py
- swagger.json
> fix: add "rsuId"&&"areaCode" to query "cameras"&&"radars" list

- dandelion/api/api_v1/endpoints/rsu_queries.py
- dandelion/crud/crud_rsu_query.py
- dandelion/crud/crud_rsu_query_result.py
- dandelion/mqtt/service/query/rsu_query_up.py
- swagger.json
> fix: add delete api to RSU Query && Query list in reverse order

- dandelion/api/api_v1/endpoints/rsus.py
- dandelion/main.py
- dandelion/periodic_tasks.py
- dandelion/schemas/__init__.py
- dandelion/schemas/rsu.py
- requirements.txt
- swagger.json
> feat: add polling collect device information to RSU

- dandelion/api/api_v1/endpoints/system_configs.py
- dandelion/mqtt/service/algorithm/system_config.py
> feat: add MQTT Notice to update system_config

- dandelion/api/api_v1/endpoints/cloud_homes.py
> fix: query camera and radar offline number

- dandelion/models/rsu.py
- dandelion/schemas/rsu.py
- swagger.json
> fix: add "rsuModelName" to RSU detailed results (#20)

- dandelion/api/api_v1/endpoints/cameras.py
- dandelion/api/api_v1/endpoints/radars.py
- dandelion/crud/crud_camera.py
- dandelion/crud/crud_radar.py
- swagger.json
> fix: add "rsuId"&"areaCode" to query "cameras"&"radars" list (#21)

- dandelion/api/api_v1/endpoints/rsu_queries.py
- dandelion/crud/crud_rsu_query.py
- dandelion/crud/crud_rsu_query_result.py
- dandelion/mqtt/service/query/rsu_query_up.py
- swagger.json
> fix: add delete api to RSU Query && Query list in reverse order (#23)

- dandelion/api/api_v1/endpoints/rsus.py
- dandelion/main.py
- dandelion/periodic_tasks.py
- dandelion/schemas/__init__.py
- dandelion/schemas/rsu.py
- requirements.txt
- swagger.json
> feat: add polling collect device information to RSU (#24)

- dandelion/api/api_v1/endpoints/system_configs.py
- dandelion/mqtt/service/algorithm/system_config.py
> feat: add MQTT Notice to update system_config (#28)

- dandelion/api/api_v1/endpoints/rsi_dnps.py
- dandelion/api/api_v1/endpoints/rsi_events.py
- dandelion/api/api_v1/endpoints/rsm_participants.py
- dandelion/crud/crud_rsi_dnp.py
- dandelion/crud/crud_rsi_event.py
- dandelion/crud/crud_rsm_participant.py
- dandelion/schemas/utils.py
- swagger.json
> fix: add sort to Event list (#34)

- doc/catalog-tree.md
- doc/dandelion.md
- doc/how-to-develop.md
- doc/technology-stack.md
> doc: add doc introduction

- dandelion/api/api_v1/endpoints/system_configs.py
- dandelion/mqtt/service/algorithm/system_config.py
- dandelion/mqtt/service/cloud/edge_info_ack.py
> fix: Modify system config notification timing

- dandelion/api/api_v1/endpoints/system_configs.py
- dandelion/mqtt/service/algorithm/system_config.py
- dandelion/mqtt/service/cloud/edge_info_ack.py
> fix: modify notification timing to system config (#51)

- dandelion/alembic/env.py
- dandelion/db/session.py
cherry pick: #50 
closes #46
Co-authored-by: qiaolei <qiao.lei@99cloud.net>
> fix: mysql password supports special characters (#50)

- dandelion/db/redis_pool.py
- dandelion/db/session.py
> fix: redis and mysql support [\/:

- dandelion/api/api_v1/endpoints/system_configs.py
> fix: modify edge site name,the old and new data exist at the same time

- dandelion/db/redis_pool.py
- dandelion/db/session.py
cherry pick: #62 
closes #59
Co-authored-by: qiaolei <qiao.lei@99cloud.net>
> fix: redis and mysql support [\/: (#61)

- dandelion/alembic/env.py
> fix: special handling of sqlite connections

- dandelion/api/api_v1/endpoints/system_configs.py
- dandelion/conf/role.py
- dandelion/main.py
- dandelion/mqtt/cloud_server.py
- dandelion/mqtt/server.py
- dandelion/schemas/system_config.py
- etc/dandelion/dandelion.conf.sample
> fix: the main site cannot connect to subsite

- dandelion/api/api_v1/endpoints/system_configs.py
- dandelion/conf/__init__.py
- dandelion/conf/mode.py
- dandelion/main.py
- dandelion/mqtt/cloud_server.py
- dandelion/mqtt/server.py
- etc/dandelion/dandelion.conf.sample
- swagger.json
1. coexist suppose do not need register
2. comment coexist mode
3. rename role to mode
4. need a refactor later
> fix: coexist mode register failure

- dandelion/api/api_v1/endpoints/rsu_tmps.py
- swagger.json
> feat: add delete to tmp_rsu

- dandelion/api/api_v1/endpoints/system_configs.py
- dandelion/main.py
- dandelion/mqtt/server.py
- dandelion/mqtt/service/cloud/edge_delete.py
- dandelion/mqtt/topic/v2x_edge.py
- dandelion/periodic_tasks.py
> fix: remove edges when modifying configuration

- dandelion/api/api_v1/endpoints/rsus.py
> fix: edge add RSU center not showing

- dandelion/mqtt/server.py
- dandelion/mqtt/service/cloud/edge_info_ack.py
> fix: wrong MQTT message sent when modifying SystemConfig

- dandelion/mqtt/topic/v2x_edge.py
cherry pick: #63 
Co-authored-by: qiaolei <qiao.lei@99cloud.net>
> fix: remove extra ， (#63)

- dandelion/mqtt/__init__.py
- dandelion/mqtt/cloud_server.py
- dandelion/mqtt/server.py
- dandelion/mqtt/service/cloud/edge_forward.py
- dandelion/mqtt/service/cloud/edge_info_ack.py
- dandelion/mqtt/service/map/map_down.py
- dandelion/mqtt/service/query/__init__.py
- dandelion/mqtt/service/rsu/rsu_config.py
- dandelion/periodic_tasks.py
> fix: modify system_config to send error MQTT

- dandelion/api/api_v1/endpoints/system_configs.py
- dandelion/conf/role.py
- dandelion/main.py
- dandelion/mqtt/cloud_server.py
- dandelion/mqtt/server.py
- dandelion/schemas/system_config.py
- etc/dandelion/dandelion.conf.sample
> fix: the main site cannot connect to subsite (#68)

- dandelion/api/api_v1/endpoints/system_configs.py
- dandelion/conf/__init__.py
- dandelion/conf/mode.py
- dandelion/main.py
- dandelion/mqtt/cloud_server.py
- dandelion/mqtt/server.py
- etc/dandelion/dandelion.conf.sample
- swagger.json
1. coexist suppose do not need register
2. comment coexist mode
3. rename role to mode
4. need a refactor later
cherry pick: #72
> fix: coexist mode register failure (#72)

- dandelion/api/api_v1/endpoints/system_configs.py
- dandelion/main.py
- dandelion/mqtt/server.py
- dandelion/mqtt/service/cloud/edge_delete.py
- dandelion/mqtt/topic/v2x_edge.py
- dandelion/periodic_tasks.py
> fix: remove edges when modifying configuration (#74)

- dandelion/api/api_v1/endpoints/rsus.py
- dandelion/crud/utils.py
> fix: failed to create RSU

- README-zh_CN.rst
- README.rst
> docs: fix sample file name error

- dandelion/mqtt/__init__.py
- dandelion/mqtt/cloud_server.py
- dandelion/mqtt/server.py
- dandelion/mqtt/service/cloud/edge_forward.py
- dandelion/mqtt/service/cloud/edge_info_ack.py
- dandelion/mqtt/service/map/map_down.py
- dandelion/mqtt/service/query/__init__.py
- dandelion/mqtt/service/rsu/rsu_config.py
- dandelion/periodic_tasks.py
1、change the function name to lowercase
closes #83
cherry pick: #87
> fix: modify system_config to send error MQTT (#87)

- dandelion/api/api_v1/endpoints/rsus.py
- dandelion/crud/utils.py
> fix: failed to create RSU (#95)

- .github/workflows/apitest.yml
- apitest/area.yaml
- apitest/camera.yaml
- apitest/cloud_home.yaml
- apitest/map.yaml
- apitest/map_rsu.yaml
- apitest/mng.yaml
- apitest/radar.yaml
- apitest/rsi.yaml
- apitest/rsi_dnp.yaml
- apitest/rsm.yaml
- apitest/rsu.yaml
- apitest/rsu_config.yaml
- apitest/rsu_log.yaml
- apitest/rsu_model.yaml
- apitest/rsu_query.yaml
- apitest/rsu_tmp.yaml
- apitest/user_login.yaml
> feat: add apitest check

- .vscode/launch.json
- dandelion/api/deps.py
disable auth logic if env var OPENV2X_DANDELION_NO_AUTH=true
> feat: add noauth support for debugging scenario

- dandelion/api/api_v1/endpoints/system_configs.py
- dandelion/mqtt/service/rsu/rsu_algo.py
> fix: using edge mqtt to send message

- .github/workflows/apitest.yml
- test-requirements.txt
> fix: pip install -r test-requirements.txt replace pip install gabbi in
